---

- name: Install epel-release
  package: name=epel-release state=latest

- name: Install required software packages
  package: name={{ item }} state=installed
  with_items:
  - git
  - gcc
  - libabw
  - curl
  - python-devel
  - python-pip
  - nodejs
  - ansible

- name: create etherpad-lite user
  user: name=etherpad-lite shell=/bin/bash

- name: lock etherpad-lite user's password
  command: passwd -l etherpad-lite

- name: check out etherpad-lite code
  git: repo=https://github.com/ether/etherpad-lite.git dest=/opt/etherpad-lite version={{ etherpad_version }}

- name: create log directory
  file: path=/var/log/etherpad-lite owner=etherpad-lite group=etherpad-lite state=directory

- name: update permissions for etherpad-lite directory
  file: path=/opt/etherpad-lite owner=etherpad-lite group=etherpad-lite recurse=yes state=directory

- name: create etherpad-lite startup script
  copy: src=etc_init_etherpad-lite dest=/etc/init.d/etherpad-lite mode=0755

- name: create ansible directory
  file: path=/setup state=directory owner=etherpad-lite group=root mode=0775

- name: copy files
  copy:
    src: "{{ item }}"
    dest: /setup/
    owner: etherpad-lite
    group: root
    mode: 0644
  with_fileglob:
    - "./"


# - name: copy etherpad-lite settings template
#   copy: src=opt_etherpad-lite_settings.json.j2 dest=/setup/settings.json.j2

# - name: copy etherpad-lite initialization playbook
#   copy: src=initialize.yml dest=/setup/initialize.yml

# - name: write inventory file
#   copy:
#     content: |
#       localhost
#     dest: /setup/inventory

- name: copy entrypoint script
  copy:
    src: entrypoint.sh
    dest: /usr/bin/entrypoint.sh
    owner: etherpad-lite
    group: root
    mode: 0775
