---

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get environment variables
      set_fact:
        db_user: "{{ lookup('env', 'DATABASE_USER') }}"
        db_host: "{{ lookup('env', 'DATABASE_HOST') }}"
        db_password: "{{ lookup('env', 'DATABASE_PASSWORD') }}"
        db_name: "{{ lookup('env', 'DATABASE_NAME') }}"
        session_key: "{{ lookup('env', 'SESSION_KEY') }}"
        padadmin_password: "{{ lookup('env', 'ADMIN_PASSWORD') }}"

    - name: template settings
      template:
        src: /setup/settings.json.j2
        dest:  /opt/etherpad-lite/settings.json
        mode: 0640
        owner: etherpad-lite
        group: etherpad-lite
